name: Sovrin Push 

on: 
  push:

jobs:
  extract-information:
    name: Extract needed Information for Indy-Test-Automation
    runs-on: ubuntu-latest
    outputs:
      indyVersion: ${{ steps.indy-versions.outputs.indyVersion}}
      sovtokenVersion: ${{ steps.sovtoken-versions.outputs.sovtokenVersion}}
      sovtokenfeesVersion: ${{ steps.sovtoken-versions.outputs.sovtokenfeesVersion}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare
        run: ./build-scripts/ubuntu-1604/prepare-package.sh ./ "1.2.0"
      - name: Extract Indy Versions
        id: indy-versions
        run:  |
          echo "indyVersion=$(grep -oP "\d+.\d+.\d+((-|.)?rc\d+)?" <<< $(grep -oP "indy-node==\d+.\d+.\d+((-|.)?rc\d+)?" setup.py))" >>$GITHUB_OUTPUT
      - name: Extract sovtoken & sovtokenfees Version
        id: sovtoken-versions
        run: |
          echo "sovtokenVersion=$(grep -oP "\d+.\d+.\d+((-|.)?((rc)|(dev))?\d+)?" <<< $(grep -oP "sovtoken==\d+.\d+.\d+((-|.)?(rc|dev)\d+)?" setup.py))" >>$GITHUB_OUTPUT
          echo "sovtokenfeesVersion=$(grep -oP "\d+.\d+.\d+((-|.)?((rc)|(dev))?\d+)?" <<< $(grep -oP "sovtokenfees==\d+.\d+.\d+((-|.)?(rc|dev)\d+)?" setup.py))" >>$GITHUB_OUTPUT
  build_sovrin:
    name: Build Sovrin Deb
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          sudo apt-get update && sudo apt-get -y install rubygems
          sudo gem install fpm
      - name: Build Sovrin Deb
        run: sudo bash ./build-scripts/ubuntu-1604/build-sovrin.sh ./ "1.2.0" $PWD/sovrin.deb
      - name: Upload sovrin.deb
        uses: actions/upload-artifact@v3
        with: 
          name: sovrin.deb
          path: ./sovrin.deb
          retention-days: 5

  call-indy-test-automation:
    name: Indy-Test-Automation
    needs: [extract-information,build_sovrin]
    uses: pschlarb/indy-test-automation/.github/workflows/sovrin.yaml@sovrin
    with:
      ubuntuVersion: "ubuntu-2004"
      libsovtokenJSON: "{\"install\": \"yes\",  \"version\": \"1.0.5\"}"
      tokenPluginJSON: "{\"install\":\"yes\", \"sovtokenVersion\": \"${{ needs.extract-information.outputs.sovtokenVersion }}\", \"sovtokenfeesVersion\":\"${{ needs.extract-information.outputs.sovtokenfeesVersion }}\"}"
      sovrinJSON: "{ \"install\": \"yes\"}"
      indyJSON: "{ \"nodeVersion\": \"${{ needs.extract-information.outputs.indyVersion }}\", \"plenumVersion\" : \"1.13.1~rc2\", \"ursaVersion\": \"0.3.2-1\", \"pyzmqVersion\" : \"22.3.0\"}"
      libIndyVersion: "1.15.0~1625-bionic"
      testAutomationBranch: "sovrin"